apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-malicious-deployment
  labels:
    app: demo-malicious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-malicious
  template:
    metadata:
      labels:
        app: demo-malicious
    spec:
      containers:
        - name: demo-replicaset
          image: arwthomasm/ckp-bootcamp-demo:malicious
          imagePullSecrets:
            - name: regcred
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: demo-malicious-svc
  namespace: ckp-bootcamp
  labels:
    name: demo-malicious-svc
    app: demo-malicious
spec:
  type: ClusterIP
  selector:
    app: demo-malicious
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-malicious-route
  namespace: ckp-bootcamp
  labels:
    name: demo-malicious-route
    app: demo-malicious
spec:
  host: malicious.apps.test.ocp4.tm.lab
  to:
    kind: Service
    name: demo-malicious-svc
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
