FROM ubuntu

RUN apt-get update && \
    apt-get install -y \
        vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN addgroup --gid 1001 thomas && \
    adduser --disabled-password --shell /bin/bash -uid 1001 --gid 1001 --home /data --gecos "" thomas

USER thomas

CMD ["bash"]
