apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-replicaset
  labels:
    app: demo-replicaset
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 20
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: demo-replicaset
        tier: frontend
    spec:
      containers:
        - name: demo-replicaset
          image: arwthomasm/ckp-bootcamp-demo:replicaset-v2
          imagePullSecrets:
            - name: regcred
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-replicaset-svc
  namespace: ckp-bootcamp
  labels:
    name: demo-replicaset-svc
    app: demo-replicaset
spec:
  type: NodePort
  selector:
    app: demo-replicaset
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-replicaset-route
  namespace: ckp-bootcamp
  labels:
    name: demo-replicaset-route
    app: demo-replicaset
spec:
  host: replicaset.apps.test.ocp4.tm.lab
  to:
    kind: Service
    name: demo-replicaset-svc
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
